#!/usr/bin/env node

import { access, readFile, writeFile } from "node:fs/promises"
import { constants } from "node:fs"
import path from "node:path"
import process from "node:process"

const args = process.argv.slice(2)
const knownOptions = new Set(["--force", "--dry-run", "-h", "--help"])
const unknownOption = args.find(
  (arg) => arg.startsWith("-") && !knownOptions.has(arg)
)

if (unknownOption) {
  console.error(`Error: unknown option '${unknownOption}'.`)
  process.exit(1)
}

if (args.includes("-h") || args.includes("--help")) {
  console.log(`Usage:
  node scripts/configure-project.mjs <project-directory> [--force] [--dry-run]

Validate a Vite + Tailwind 4 + shadcn Base UI project, generate the
vite.singlefile.config.ts overlay, and add the build:single package script.

Options:
  --force    Replace an existing overlay.
  --dry-run  Print planned file changes without writing.

This script is normally called through scripts/configure-project.sh.`)
  process.exit(0)
}

const projectArg = args.find((arg) => !arg.startsWith("-"))
const force = args.includes("--force")
const dryRun = args.includes("--dry-run")

if (!projectArg) {
  console.error(
    "Usage: node configure-project.mjs <project-directory> [--force]"
  )
  process.exit(1)
}

const projectDir = path.resolve(projectArg)
const packagePath = path.join(projectDir, "package.json")
const componentsPath = path.join(projectDir, "components.json")
const indexPath = path.join(projectDir, "index.html")
const overlayPath = path.join(projectDir, "vite.singlefile.config.ts")

async function exists(filePath) {
  try {
    await access(filePath, constants.F_OK)
    return true
  } catch {
    return false
  }
}

if (!(await exists(packagePath))) {
  throw new Error(`package.json not found in ${projectDir}`)
}

const packageJson = JSON.parse(await readFile(packagePath, "utf8"))
const allDependencies = {
  ...packageJson.dependencies,
  ...packageJson.devDependencies,
}

for (const dependency of [
  "react",
  "vite",
  "tailwindcss",
  "@tailwindcss/vite",
  "shadcn",
  "@base-ui/react",
]) {
  if (!allDependencies[dependency]) {
    throw new Error(
      `Missing ${dependency}. This skill requires Vite, Tailwind 4, ` +
        "shadcn, and Base UI."
    )
  }
}

if (!allDependencies["vite-plugin-singlefile"] && !dryRun) {
  throw new Error(
    "Missing vite-plugin-singlefile. Run configure-project.sh so the pinned " +
      "dependency is installed before writing the overlay."
  )
}

if (!(await exists(componentsPath))) {
  throw new Error("components.json not found. Initialize shadcn first.")
}

const components = JSON.parse(await readFile(componentsPath, "utf8"))
if (
  components.base !== "base" &&
  !String(components.style ?? "").startsWith("base-")
) {
  throw new Error(
    "This shadcn project is not configured for Base UI. " +
      "Initialize or migrate it with shadcn --base=base first."
  )
}

if (await exists(indexPath)) {
  const indexHtml = await readFile(indexPath, "utf8")
  let updatedIndexHtml = indexHtml.replace(
    /^\s*<link\s+rel=["']icon["']\s+type=["']image\/svg\+xml["']\s+href=["']\/vite\.svg["']\s*\/?>\s*\n?/m,
    ""
  )

  if (!/<link\b[^>]*\brel=["'][^"']*\bicon\b[^"']*["']/i.test(updatedIndexHtml)) {
    updatedIndexHtml = updatedIndexHtml.replace(
      /(<meta\s+charset=["'][^"']+["']\s*\/?>)/i,
      '$1\n    <link rel="icon" href="data:,">'
    )
  }

  updatedIndexHtml = updatedIndexHtml.replace(
    /<title>\s*(?:vite-app|vite\s*\+\s*react(?:\s*\+\s*ts)?)\s*<\/title>/i,
    `<title>${packageJson.name}</title>`
  )

  if (updatedIndexHtml !== indexHtml) {
    if (dryRun) {
      console.log("Would replace Vite starter metadata in index.html")
    } else {
      await writeFile(indexPath, updatedIndexHtml)
      console.log("Replaced Vite starter metadata in index.html")
    }
  }
}

const configCandidates = [
  "vite.config.ts",
  "vite.config.mts",
  "vite.config.js",
  "vite.config.mjs",
  "vite.config.cts",
  "vite.config.cjs",
]

const existingConfigs = []
for (const candidate of configCandidates) {
  if (await exists(path.join(projectDir, candidate))) {
    existingConfigs.push(candidate)
  }
}

if (existingConfigs.length > 1) {
  throw new Error(
    `Multiple Vite configs found: ${existingConfigs.join(", ")}. ` +
      "Keep one canonical config before adding the single-file overlay."
  )
}

const baseConfigName = existingConfigs[0]
const baseImport = baseConfigName
  ? `import baseConfigExport from ${JSON.stringify(`./${baseConfigName}`)}\n`
  : ""
const baseResolution = baseConfigName
  ? `  const baseConfig =
    typeof baseConfigExport === "function"
      ? await baseConfigExport(env)
      : await baseConfigExport
`
  : "  const baseConfig = {}\n"

const overlaySource = `// Generated by the ui-prototype skill.
// Keep application-specific configuration in the canonical Vite config.
import { defineConfig, mergeConfig } from "vite"
import { viteSingleFile } from "vite-plugin-singlefile"
${baseImport}
export default defineConfig(async (env) => {
${baseResolution}
  const outputDirectory = process.env.UI_PROTOTYPE_BUILD_DIR
  if (!outputDirectory) {
    throw new Error(
      "UI_PROTOTYPE_BUILD_DIR is required. " +
        "Run the build through scripts/build-single-html.sh."
    )
  }

  return mergeConfig(baseConfig ?? {}, {
    base: "./",
    publicDir: false,
    plugins: [
      viteSingleFile({
        useRecommendedBuildConfig: true,
      }),
    ],
    build: {
      outDir: outputDirectory,
      emptyOutDir: true,
      assetsInlineLimit: () => true,
      cssCodeSplit: false,
      sourcemap: false,
    },
  })
})
`

if ((await exists(overlayPath)) && !force) {
  console.log(
    "Keeping existing vite.singlefile.config.ts. Use --force to replace it."
  )
} else if (dryRun) {
  console.log(`Would write ${overlayPath}`)
} else {
  await writeFile(overlayPath, overlaySource)
  console.log(`Wrote ${overlayPath}`)
}

packageJson.scripts ??= {}
packageJson.scripts["build:single"] =
  "vite build --config vite.singlefile.config.ts"
if (dryRun) {
  console.log("Would add or update package script: build:single")
  console.log("Dry run complete. No files were written.")
} else {
  await writeFile(packagePath, `${JSON.stringify(packageJson, null, 2)}\n`)
  console.log("Added package script: build:single")
}
